# Generated by Django 5.1.5 on 2025-01-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='MushroomProduct',
        ),
    ]
